Vagrant.configure("2") do |config|
  # Configuration de la VM Maître
  config.vm.define "maxS" do |master|
    master.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 LTS
    master.vm.hostname = "maxS"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
  end

  # Configuration de la VM Nœud
  config.vm.define "maxSW" do |node|
    node.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 LTS
    node.vm.hostname = "maxSW"
    node.vm.network "private_network", ip: "192.168.56.111"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
  end
end