Vagrant.configure("2") do |config|

    # Configuration de la VM Master
    config.vm.define "mbrignolS" do |master|
        master.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 LTS
        master.vm.hostname = "mbrignolS"
        master.vm.network "private_network", ip: "192.168.56.110"
        master.vm.provider "virtualbox" do |vb|
            vb.name = "mbrignolS"
            vb.memory = "2048"
            vb.cpus = 4
        end

        master.vm.provision "shell", path: "scripts/k3s-master.sh"
    end

    #   Configuration de la VM Worker
    config.vm.define "mbrignolSW" do |worker|
        worker.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 LTS
        worker.vm.hostname = "mbrignolSW"
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.provider "virtualbox" do |vb|
            vb.name = "mbrignolSW"
            vb.memory = "1024"
            vb.cpus = 2
        end

        worker.vm.provision "shell", path: "scripts/k3s-worker.sh", args: ["192.168.56.110"]
    end


end