Vagrant.configure("2") do |config|

    config.vm.define "bonus" do |host|
        host.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 LTS
        host.vm.hostname = "bonus"
        host.vm.network "private_network", ip: "192.168.56.130"
        host.vm.provider "virtualbox" do |vb|
            vb.name = "bonus"
            vb.memory = "12288"
            vb.cpus = 8
        end

        host.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    end

end